#!/Library/Frameworks/Python.framework/Versions/3.13/bin/python3

from xml.etree.ElementTree import parse
import os
import time
import pandas as pd

start = time.perf_counter()
document = parse('swissprot.xml')
#for item in document.iterfind('book'):
#    print(item)

#for item in document.iterfind('book'):
#    print(item.findtext('author'))

ac = []
author = []
title = []
year = []

for item in document.iterfind('Entry'):
    ac.append(item.findtext('AC'))

df = pd.DataFrame({'AC': ac})
print(df)

end = time.perf_counter()

duration = end - start
print(f'Took {duration:.3f} seconds')
time.sleep(5)
